name: deploy

# 代码提交到main分支时触发github action
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
              fetch-depth: 0
              submodules: recursive  # 添加这一行然后一次执行以下命令（会删除原本的主题文件，使用go modules进行管理，保证能读取所有的主题子模块）：
              git rm -r --cached themes/hugo-theme-stack
              rm -rf themes/hugo-theme-stack
              git submodule add https://github.com/CaiJimmy/hugo-theme-stack.git themes/hugo-theme-stack
              git add .
              git commit -m "fix: correctly add theme submodule"
              git push origin main

        - name: Setup Hugo
          uses: peaceiris/actions-hugo@v3
          with:
              hugo-version: "latest"
              extended: true

        - name: Build Web
          run: hugo -D

        - name: Deploy Web
          uses: peaceiris/actions-gh-pages@v4
          with:
              PERSONAL_TOKEN: ${{ secrets.ACTION_ACCESS_TOKEN }}
              EXTERNAL_REPOSITORY: ShifanShen/ShifanShen.github.io
              PUBLISH_BRANCH: main
              PUBLISH_DIR: ./public
              commit_message: auto deploy
